#!/usr/bin/env bash
# A Bash script that displays all running processes in a user-oriented format with hierarchy including processes without a TTY.

ps -eo user,start,%cpu,%mem,vsz,rss,tty,stat,time,cmd --forest | awk 'NR==1{$2="STARTED"; print; next} {print}'
