#!/usr/bin/env bash
# A Bash script that displays all running processes in a user-oriented format with hierarchy including processes without a TTY.

echo "USER STARTED CMD"

ps -eo user,lstart,args --no-headers | awk '{
    user = $1;
    started = $5;   # Extract HH:MM:SS
    cmd = "";
    for (i = 6; i <= NF; i++) {
        cmd = cmd $i " ";
    }
    gsub(/[ \t]+$/, "", cmd);  # Remove trailing space
    printf "%s %s %s\n", user, started, cmd;
}'
