#!/usr/bin/env bash
# script that displays “Best School” 10 times. However, for the 9th iteration, the script should display “Best School” and then, on a new line, display “Hi”.
i=1
while [ $i -le 10 ]
do
  echo "Best School"

  if [ $i -eq 9  ]; then
    echo "Hi"
  fi

  i=$((i + 1))
done
