#!/usr/bin/env bash
# Check that it is not a directory and contains a dash

for file in *; do
  
  if [[ "$file" != .* ]]; then
    
    case "$file" in
      *-*) echo "${file#*-}" ;;
      *) echo "$file" ;;
    esac
  fi
done

